version: 2
sources:
  - name: movielens_brut
    schema: raw_data
    tables:
      - name: movies
        columns:
          - name: movie_id
            tests:
              - unique
              - not_null
      - name: ratings
        columns:
          - name: user_id
            tests:
              - not_null
          - name: movie_id
            tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('movielens_brut', 'movies')
                    field: movie_id
          - name: rating
            tests:
              - not_null
      - name: links
        columns:
          - name: movie_id
            tests:
              - not_null